name: Deploy to GitHub Pages
debug_info:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug Information
        run: |
          pwd
          ls -la
          ls -la /
          ls -la /home/runner/work/ratatype_test/ratatype_test
          npm --version
          node --version
          npm list

